# Generated by Django 5.1.3 on 2024-11-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "description",
                    models.TextField(max_length=255, verbose_name="Описание"),
                ),
                ("preview", models.ImageField(upload_to="lesson_previews/")),
                ("link_video", models.URLField()),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("preview", models.ImageField(upload_to="previews/")),
                (
                    "description",
                    models.TextField(max_length=255, verbose_name="Описание"),
                ),
                (
                    "lessons",
                    models.ManyToManyField(
                        related_name="courses", to="education.lesson"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
    ]
